{{- if and .Values.postgres.enabled .Values.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "re-rotas.postgresPvcName" . }}
  labels:
    {{- include "re-rotas.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
  {{- with .Values.postgres.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
